# 1. Getting Started

(**To start, we import the PyTorch library.
Note that the package name is `torch`.**)



In [1]:
import torch

## Definition

In [3]:
# TODO: 创建一个 0-11 的一维张量x
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Access Shape and Size

In [8]:
# TODO: 查看x的元素总数
num_elements = x.numel()
print(num_elements)

12


In [9]:
# TODO: 查看x的形状
x_shape = x.shape
print(x_shape)

torch.Size([12])


# 2. Data Manipulation
## Reshaping Tensors

In [10]:
# TODO: 将上面创建的一维张量x变成 3 行 4 列的二维张量
X = torch.reshape(x, (3, 4))
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## Initializing Tensors

In [11]:
# TODO: 创建所有元素均为0的张量tensor_zeros
tensor_zeros = torch.zeros((3, 4))
print("Zero Tensor:", tensor_zeros)

Zero Tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Similarly, we can create a tensor 
with all 1s by invoking `ones`.


In [12]:
# TODO: 创建所有元素均为1张量tensor_ones
tensor_ones = torch.ones((3, 4))
print("Ones Tensor:", tensor_ones)

Ones Tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [13]:
# TODO: 创建一个 3x4 的标准正态分布随机张量tensor_randn
tensor_randn = torch.randn((3, 4))
print("Random Normal Tensor:", tensor_randn)

Random Normal Tensor: tensor([[ 0.4109, -0.2651, -1.1626, -1.6206],
        [ 0.2307, -0.3493,  0.2292,  0.1589],
        [ 0.6694, -1.4305, -0.5743,  0.8233]])


## Create TenCreate Tensor from other data structure

In [14]:
A  = [[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]
print("The type of A is:", type(A))
# TODO: 将Python列表A转换为张量A
A = torch.tensor(A)
print("The type of A is:", type(A))

A  = A.numpy()
print("The type of A is:", type(A))
# TODO: 将NumPy数组A转换为张量A
A = torch.tensor(A)
print("The type of A is:", type(A))

The type of A is: <class 'list'>
The type of A is: <class 'torch.Tensor'>
The type of A is: <class 'numpy.ndarray'>
The type of A is: <class 'torch.Tensor'>


## Indexing

In [16]:
A = torch.tensor([
    [32, 27,  5, 54,  1],
    [99,  4, 23,  3, 57],
    [76, 42, 34, 82,  5]
])

In [17]:
# TODO: 访问[0,3]位置的元素
element = A[0,3] 
print(element)

tensor(54)


In [20]:
# TODO: 获取第4列
row_3 = A[:,3]
print(row_3)

tensor([54,  3, 82])


In [21]:
# TODO: 获取第0行
column = A[0,:]
print(column)

tensor([32, 27,  5, 54,  1])


In [22]:
# TODO: 获取第0行的[2:4]的元素
elements =  A[0,2:4]
print(elements)

tensor([ 5, 54])


In [23]:
# TODO: 获取最后一行
row_last = A[-1:]
print(row_last)

tensor([[76, 42, 34, 82,  5]])


In [ ]:
# TODO: 获取1到3行
rows = A[1:4,:]
print(rows)

tensor([[99,  4, 23,  3, 57],
        [76, 42, 34, 82,  5]])


## Assigning Values

In [26]:
X = torch.tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
# TODO: 将(1.2)位置上的值变成9
X[1,2] = 9
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


In [28]:
# TODO: 将前两行所有值变成12
X[0:2,:] = 12
print(X)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## Mathematical Operations


In [29]:
# TODO: 计算张量 X 中每个元素的指数（e^x）
X_exp = torch.exp(X)
print(X_exp)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])


In [30]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
# TODO: 将x和y中每个元素分别进行加减乘除
result_add = x + y
result_sub = x - y
result_mul = x * y
result_div = x / y

print(result_add)
print(result_sub)
print(result_mul)
print(result_div)

tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])


# Concatenation and Splitting of Tensors

In [32]:

A = torch.tensor([[1,2],[3,4]])
B=torch.tensor([[5,6],[7,8]])
# TODO: 将x和y分别在行维度和列维度拼接
xy_row = torch.cat((A, B), dim=0)
xy_col = torch.cat((A, B), dim=1)
print(xy_row)
print(xy_col)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [37]:
Z=torch.arange(12).reshape(3,4)
print(Z)
# TODO: 按照列维度进行拆分，拆分后每个张量每行元素均包含 2 列
split_result = torch.split(Z, 2, dim=1)
print(split_result)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
(tensor([[0, 1],
        [4, 5],
        [8, 9]]), tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]]))


## Broadcasting




In [39]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [40]:
# TODO: 将a和b相加
broadcast_result = a+b
print(broadcast_result)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


## Conversion to Other Python Objects


In [41]:
# TODO: 将X转换为 NumPy 数组A，接着再从 NumPy 数组A 转换为 Tensor B
A = X.numpy()
B = torch.from_numpy(A)
print(A)
print(B)

[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [45]:
a = torch.tensor([3.5])
# TODO: 将a分别转换为float和int类型的变量
a_float = float(a)
a_int = int(a)
print(type(a_float))
print(type(a_int))

<class 'float'>
<class 'int'>


# 3. Data Preprocessing


## Reading the Dataset

In [2]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

Now let's import `pandas` and load the dataset with `read_csv`.


In [3]:
import pandas as pd

# TODO: 使用pandas读取数据data_file
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


## Data Preparation


In [4]:
# TODO: 将data分成inputs（取data数据的前2列）和targets（取data数据的第3列）
inputs = data.iloc[:, 0:2]
targets = data.iloc[:, 2]

print(inputs)
print(targets)

   NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


In [5]:
# TODO: 使用pandas库中的get_dummies函数将inputs转换为独热编码（缺失值也考虑）
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)


   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


## Conversion to the Tensor Format


In [11]:
import torch

# TODO: 将inputs和targets转换为张量格式, X是input, y是target
X = torch.tensor(inputs.to_numpy(dtype=float), dtype=torch.float16)
y = torch.tensor(targets.to_numpy(dtype=float), dtype=torch.float16)
print(X)
print(y)

tensor([[3., 0., 1.],
        [2., 0., 1.],
        [4., 1., 0.],
        [3., 0., 1.]], dtype=torch.float16)
tensor([inf, inf, inf, inf], dtype=torch.float16)


In [7]:
# TODO: 将inputs中的缺失值用非空样本的均值代替
inputs = inputs.fillna(inputs.mean()) 
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


## Exercises



### Exercise 1: Tensor Shape Manipulation


In [83]:
# TODO: 创建一个包含0到23的张量，并将其重新塑形为 (2, 3, 4) 形状。
# HINT: 使用 torch.arange() 和 reshape() 方法。
#--------- write your answer below --------
X = torch.arange(24).reshape((2, 3, 4))
print("Exercise 1 Output:")
print(X)

Exercise 1 Output:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### Exercise 2: Indexing and Slicing

In [84]:
# TODO: 从给定的张量中提取第二行、最后两列。
# HINT: 使用索引和切片表示法。
X = torch.tensor([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
#--------- write your answer below --------
second_row = X[1, :]
last_two_columns = X[:, -2:]
print("\nExercise 2 Output:")
print("Second row:", second_row)
print("Last two columns:\n", last_two_columns)


Exercise 2 Output:
Second row: tensor([50, 60, 70, 80])
Last two columns:
 tensor([[ 30,  40],
        [ 70,  80],
        [110, 120]])


### Exercise 3: Elementwise Operations

In [ ]:
# TODO: 计算 A 和 B 的加法、乘法、指数、点积和余弦相似度。
# HINT: 使用 +, *, ** 运算符，以及 torch.dot() 和 torch.nn.functional.cosine_similarity()。
A = torch.tensor([2, 4, 6, 8])
B = torch.tensor([1, 2, 3, 4])
#--------- write your answer below --------
addition = A + B
multiplication = A * B
exponentiation = A ** B
dot_product = torch.dot(A, B)
cosine_similarity = torch.nn.functional.cosine_similarity(A.to(dtype=torch.float32), B.to(dtype=torch.float32), dim=0)
# cosine_similarity 属于神经网络模块，通常默认处理的是**批量（Batch）**数据，所以强制要求浮点型以保证精度。
print("\nExercise 3 Output:")
print("Addition:", addition)
print("Multiplication:", multiplication)
print("Exponentiation:", exponentiation)
print("Dot Product:", dot_product)
print("Cosine Similarity:", cosine_similarity)

ValueError: only one element tensors can be converted to Python scalars

### Exercise 4: Broadcasting

In [91]:
# TODO: 使用广播机制进行a和b的逐元素加法，并计算 a 和 b 的逐列均值。
# HINT: 使用广播进行加法，并使用 torch.mean() 计算均值。
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([10, 20, 30])
#--------- write your answer below --------
result = a + b
column_mean = torch.mean(result.to(dtype=torch.float32), dim=0)
print("\nExercise 4 Output:")
print("Broadcasted Addition:")
print(result)
print(column_mean.shape)
print("Column Mean:", column_mean)


Exercise 4 Output:
Broadcasted Addition:
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
torch.Size([3])
Column Mean: tensor([12., 22., 32.])
